# Generated by Django 6.0.1 on 2026-02-24 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='CardFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_link', models.ImageField(upload_to='', verbose_name='Фото')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('weight', models.CharField(max_length=200, verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.IntegerField(choices=[(1, 'Доступно'), (2, 'Нет в наличии')], verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (2, 'Подтвержден'), (3, 'Готовится'), (4, 'Готов к выдаче'), (5, 'Передан курьеру'), (6, 'Доставлен'), (7, 'Отменен')], verbose_name='Статус')),
                ('receiving', models.IntegerField(choices=[(1, 'Доставка'), (2, 'Самовывоз')], verbose_name='Тип доставки')),
                ('phone', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('pay_type', models.IntegerField(choices=[(1, 'Наличные'), (2, 'Оплата курьеру')], verbose_name='Тип оплаты')),
                ('date', models.DateTimeField(verbose_name='Дата заказа')),
                ('adress', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('finalprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardFoodCount', models.IntegerField()),
                ('CardFood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cardfood', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Ожидает подтверждения'), (2, 'Подтверждена'), (3, 'Отклонена')], default=1, verbose_name='Статус')),
                ('date', models.DateTimeField(verbose_name='Дата брони')),
                ('personcount', models.IntegerField(verbose_name='Кол-во персон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
