# Generated by Django 6.0.1 on 2026-02-24 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('count', models.CharField(max_length=200)),
                ('date_event', models.DateField(verbose_name='Дата события')),
                ('type_event', models.IntegerField(choices=[(1, 'Онлайн'), (2, 'Очная встреча')], verbose_name='Формат')),
                ('time_event', models.CharField(max_length=200, verbose_name='Длительность')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('paytype', models.IntegerField(choices=[(1, 'банковская карта'), (2, 'онлайн-перевод')], verbose_name='Способ оплаты')),
                ('status', models.IntegerField(choices=[(1, 'банковская карта'), (2, 'онлайн-перевод')], verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
